Add solution of homework 3
Otus-Android/FlowHomework pull request #15
Opened 2021-08-02 15:34 UTC by VbiterGit

2021-08-17 21:26 UTC, antonkazakov requested changes
Поправь пожалуйста замечания

2021-08-17 21:26 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
>       * При любом исходе, будь то выброс исключения или успешная отработка функции вызовите метод dotsRepository.completed()
Кажется эта задача не решена

2021-08-17 21:26 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    throw IllegalArgumentException("Failed")
Это нужно удалить)

2021-08-17 21:26 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +        val flow1 = flowOf("Red", "Green", "Blue", "Black", "White")
Можно из репозитория достать флоу

2021-08-17 21:26 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +        return (1..21).asFlow()
```kt
  return sampleRepository.produceNumbers()
            .transform {
                emit(it.toString())
                when {
                    it%15 == 0 -> emit("FizzBuzz")
                    it%5 == 0 -> emit("Buzz")
                    it%3 == 0 -> emit("Fizz")
                }
            }
```

2021-08-17 21:26 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +        return (1..21).asFlow()
Можно более короткий вариант написать не дублируя в каждой ветке `emit(it.toString())`

2021-08-18 19:23 UTC, VbiterGit commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +        val flow1 = flowOf("Red", "Green", "Blue", "Black", "White")
исправил

2021-08-18 19:23 UTC, VbiterGit commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +        return (1..21).asFlow()
Да, точно )

2021-08-18 19:23 UTC, VbiterGit commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    throw IllegalArgumentException("Failed")
исправил )

2021-08-18 19:23 UTC, VbiterGit commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
>       * При любом исходе, будь то выброс исключения или успешная отработка функции вызовите метод dotsRepository.completed()
исправил

2021-09-08 19:46 UTC, antonkazakov requested changes

2021-09-08 19:46 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    !is IllegalArgumentException -> throw it
Тут else тогда уж нужен

2021-09-08 19:46 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                sampleRepository.completed()
Получается если исключения не будет, то dotsRepository.completed() не вызовется

2021-09-08 19:46 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                when (it) {
Посмотри на https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/on-completion.html

2021-09-15 10:28 UTC, VbiterGit commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    !is IllegalArgumentException -> throw it
исправил

2021-09-15 10:29 UTC, VbiterGit commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                sampleRepository.completed()
исправил

2021-09-26 09:51 UTC, antonkazakov commented
Закрываю)

2021-09-26 09:51 UTC, closed without merging