Мои изменения
Otus-Android/FlowHomework pull request #16
Opened 2021-08-18 14:46 UTC by SpirinOleg

2021-09-26 15:09 UTC, antonkazakov requested changes

2021-09-26 15:09 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                (it % 3 != 0 && it % 5 != 0 && it % 15 != 0) -> {
Кажется тут достаточно emit(it.toString()) вынести из when блока

2021-09-26 15:09 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    if (it is IllegalArgumentException) emit(-1) else if (it !is IllegalArgumentException) {
Тут просто else хватит. Пробросить нужно это же исключение)

2021-09-28 22:21 UTC, SpirinOleg commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +        val flowColors = sampleRepository.produceColors().transform { emit(it) }
Вот сам не помню зачем. Видимо взял для преобразования и начитался вот здесь
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/transform.html?query=inline%20fun%20%3CT,%20R%3E%20Flow%3CT%3E.transform(crossinline%20transform:%20suspend%20FlowCollector%3CR%3E.(T)%20-%3E%20Unit):%20Flow%3CR%3E
Но сейчас понял, что он тут ни к чему.

2021-09-28 22:21 UTC, SpirinOleg commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                (it % 3 != 0 && it % 5 != 0 && it % 15 != 0) -> {
Исправил.

2021-09-28 22:22 UTC, SpirinOleg commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    if (it is IllegalArgumentException) emit(-1) else if (it !is IllegalArgumentException) {
Исправил.

2021-10-16 17:50 UTC, antonkazakov commented
Теперь все ок)

2021-10-16 17:50 UTC, closed without merging