Flow HW Ershov
Otus-Android/FlowHomework pull request #28
Opened 2021-10-17 14:08 UTC by georgershov

2021-10-31 12:41 UTC, antonkazakov requested changes

2021-10-31 12:41 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                val str = "${if(it % 3 == 0) "Fizz" else ""}${if(it % 5 == 0) "Buzz" else ""}"
Слушай, такую строку очень тяжело читать. Перепиши пожалуйста на if else/when вне строки

2021-10-31 12:41 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +sealed class Result
Я бы упаковывал в Result внутри презентера и распаковывал во вью, тк у тебя может быть какая то логика по запаковке именно внутри презентера, и репозиторий про нее не знает.

2021-10-31 12:41 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +sealed class Result
Например Loading.

2021-10-31 12:41 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +                when(it){
А где обработка других кейсов?

2021-10-31 14:20 UTC, georgershov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +                when(it){
ну так их всего 3 success, error, loading, ok, loading я раскомментил

2021-11-07 07:50 UTC, antonkazakov reviewed
👍

2021-11-07 07:50 UTC, closed without merging