homework Flow
Otus-Android/FlowHomework pull request #29
Opened 2021-10-17 16:26 UTC by a9992099300

2021-10-31 13:04 UTC, antonkazakov requested changes
Оставил несколько незначительных замечаний, будет круто если поправишь

2021-10-31 13:04 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    .flowOn(Dispatchers.IO)
Мне кажется лучше это перенести в listenForCatFacts. Тоесть если у тебя в listenForCatFacts блокирующий вызов то правильнее сделать так что ее можно безопасно вызывать из любого треда, а сейчас это остается на стороне подписчика

2021-11-07 15:36 UTC, a9992099300 commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +    suspend fun listenForCatFacts() = flow {
удалил suspend

2021-11-07 15:37 UTC, a9992099300 commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit(it.toString())
Исправил

2021-11-07 15:40 UTC, a9992099300 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    .flowOn(Dispatchers.IO)
Перенес flowOn(Dispatchers.IO) в listenForCatFacts(), да наверно так правильнее. Спасибо!

2021-11-14 14:49 UTC, antonkazakov commented
👍

2021-11-14 14:49 UTC, closed without merging