HW03 task 1&2
Otus-Android/FlowHomework pull request #31
Opened 2021-10-23 18:23 UTC by Dstakhanov

2021-10-31 14:18 UTC, antonkazakov requested changes
Несколько мелких замечаний. Поправь пожалуйста

2021-10-31 14:18 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                withContext(Dispatchers.IO) {
withContext(Dispatchers.IO) тебе не нужен, ты же уже флоу эмитишь на IO

2021-10-31 14:18 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            } catch (e: Throwable) {
Я советую здесь обрабатывать только какие-то ожидаемые исключения, неожидаемые же отдавать в КорутинЭксепшенХендлер

2021-10-31 14:18 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        CoroutineScope(Dispatchers.Main).launch {
Понимаю что в задании не было, но очень удобно использовать lifecycleScope, т.к. он знает про Жц компонентов и сам управляет подпиской/отпиской

2021-10-31 14:18 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$it")
Можно вынести из when

2021-10-31 18:50 UTC, Dstakhanov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                withContext(Dispatchers.IO) {
Исправил

2021-10-31 18:52 UTC, Dstakhanov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            } catch (e: Throwable) {
Поправил, наверно)

2021-10-31 18:52 UTC, Dstakhanov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        CoroutineScope(Dispatchers.Main).launch {
Исправил

2021-10-31 18:52 UTC, Dstakhanov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$it")
Исправил

2021-11-07 07:54 UTC, antonkazakov reviewed
На вопрос ответил. ПР закрываю 👍

2021-11-07 07:54 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +        Result.Error(e.message.toString())
Я думаю здесь лучше просто логировать ошибку, потому что в CoroutineExceptionHandler должны попадать необработанные выше исключения. Если что-то у тебя пойдет не так то пользователю покажется сообщения с совершенно непонятной ошибкой, а ты о ней не узнаешь. 

В catch же ты ловишь ожидаемые ошибки, на которые у тебя есть обработчик.

2021-11-07 07:59 UTC, closed without merging