first and second tasks completed
Otus-Android/FlowHomework pull request #35
Opened 2021-10-31 19:46 UTC by aaaann

first task completed
second task completed

2021-11-07 09:13 UTC, antonkazakov requested changes
Привет. Все круто, отдельный лайк за инжект диспатчеров, но с диспатчерами не. совсем понял твою идею

2021-11-07 09:13 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$it")
Можно emit вынести из when блока, чтобы не дублировать

2021-11-07 09:13 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +        const val EMPTY_STRING = ""
А зачем нужна эта константа?)

2021-11-07 09:13 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            withContext(coroutineDispatchers.ioDispatcher) {
Ты хочешь эмитить на ioDispatcher или собирать?
Я думаю правильно решение эмитить на ioDispatcher и колектить на main, но сейчас у тебя колект на ioDispatcher

2021-11-13 14:33 UTC, aaaann commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$it")
вынесла

2021-11-13 14:34 UTC, aaaann commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +        const val EMPTY_STRING = ""
используется как initialValue

2021-11-13 14:37 UTC, aaaann commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            withContext(coroutineDispatchers.ioDispatcher) {
сделала emit flow на io диспатчере через flowOn в репозитории, перевод в StateFlow через .stateIn()

2021-11-14 13:20 UTC, antonkazakov commented
👍

2021-11-14 13:20 UTC, closed without merging