Flow Homework
Otus-Android/FlowHomework pull request #37
Opened 2021-11-04 17:29 UTC by qdri1

2021-11-07 07:43 UTC, antonkazakov requested changes
Оставил пару комментариев

2021-11-07 07:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _error = MutableStateFlow<Exception?>(value = null)
Здесь хорош Result тем что не придется много флоу делать с разными типами. Сделай один который Result отправляет во View

2021-11-07 07:43 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
>      fun task4(): Flow<Int> {
dotsRepository.completed() эта задачка не реализована

2021-11-08 08:21 UTC, qdri1 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _error = MutableStateFlow<Exception?>(value = null)
сделал через sealed class-ы

2021-11-08 08:21 UTC, qdri1 commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
>      fun task4(): Flow<Int> {
done

2021-11-14 13:19 UTC, antonkazakov commented
👍

2021-11-14 13:19 UTC, closed without merging