Выполнены все пункты дз
Otus-Android/FlowHomework pull request #52
Opened 2022-02-04 16:36 UTC by PavelFedoseev

2022-02-06 18:22 UTC, antonkazakov requested changes
Привет. Оставил несколько замечаний, поправь пожалуйста

2022-02-06 18:22 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +            }
Еще здесь бы контекст переключить через flowOn, а withContext из ВьюМодели убрать

2022-02-06 18:22 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    val catsLiveData: StateFlow<Fact?> = _catsLiveData
Я бы именно тут использовал Result, из репозитория можно получить необернутый результат, обработать его в Вьюмодельке и отправить во вью на распаковку, а теперь придется добавлять логику во вью, которая проверяет null у нас заэмитился или нет

2022-02-06 18:22 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно удалить, логично здесь коллектор выполнять на диспатчере viewModelScope, а эмиттинг на другом

2022-02-06 18:22 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        CoroutineScope(Dispatchers.IO).launch {
В лайфсайкловнерах удобно использовать lifecycleScope, таким образом твои горячие флоу получают фичу лайвдаты: знают когда подписаться и когда отписаться в зависимости от ЖЦ компонента

2022-02-06 18:22 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        CoroutineScope(Dispatchers.IO).launch {
А зачем запускаешь на Dispatchers.IO?

2022-02-06 18:22 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    emit(it.toString())
emit(it.toString()) можно вынести из when блока и не дублировать

2022-02-06 18:22 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            (1..10).forEach {
Это можно убрать из финального задания и оставить (1..10).toFlow

2022-02-07 12:26 UTC, PavelFedoseev commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    val catsLiveData: StateFlow<Fact?> = _catsLiveData
Но тогда же получится, что логика обработки Result у нас будет во вью?

2022-02-13 19:35 UTC, PavelFedoseev commented
Выполнил исправления из комментариев, за исключением обработки Result, поскольку если будет Fact без ? то тогда придётся делать костыль в виде дефолтной реализации Fact в MutableStateFlow, а MutableSharedFlow не будет эмитить последний факт после переворота экрана

2022-02-20 18:26 UTC, antonkazakov requested changes
Привет. Еще пару моментов подсветил + написал свои мысли в ЛК по поводу Result

2022-02-20 18:26 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/Result.kt
> +sealed class Result<T>(val data: T? = null, val message: String? = null) {
А зачем тебе вообще в нем параметры? Кажется намного более гибко его наследникам решать нужны им параметры или нет

2022-02-20 18:26 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +                    withContext(Dispatchers.Main) { view.populate(it) }
Ты же коллект на мейн диспатчере запустил во ВьюМодели. Мне кажется здесь избыточно

2022-03-20 08:33 UTC, closed without merging